name: Release workflow

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64/v8,linux/amd64
          tags: fnxpt/cyclonedx-enrich:latest,fnxpt/cyclonedx-enrich:${{ github.ref_name }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.22.0'
    - run: go build -o dist/cyclonedx-enrich-${{ matrix.goos }}-${{ matrix.goarch }} .
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - name: Release
      uses: fnkr/github-action-ghr@v1
      env:
        GHR_COMPRESS: gz
        GHR_PATH: dist/cyclonedx-enrich-${{ matrix.goos }}-${{ matrix.goarch }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
